# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.

name: day15
synopsis: Advent of Code 2015
version: '0.0.1'


executables:
  day15:
    main: day15.hs
    source-dirs: src
    dependencies:
      - base >= 2 && < 6
      - text
      - tasty
      - containers
      - tasty-hspec
      - cond
