# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.

name: day12
synopsis: Advent of Code 2015
version: '0.0.1'


executables:
  day12:
    main: day12.hs
    source-dirs: src
    dependencies:
      - base >= 2 && < 6
      - text
      - tasty
      - split
      - containers
      - unordered-containers
      - tasty-hspec
      - safe
      - aeson
      - lens-aeson
      - bytestring
      - lens
      - scientific
